### ISSUE TITLE
ValueError: total size of new array must be unchanged

### ISSUE THREAD

**Issue by kinverarity1** [kinverarity1/las-reader#19]
```
D:\study\2015\las_kgs_test\1999\1999\1001179028.las
Traceback (most recent call last):
  File ".\basic_read_test.py", line 20, in <module>
    l = las_reader.read(fn)
  File "d:\work\dewnr\logging_software\las_reader\las_reader\__init__.py", line 5, in read
    return las.LASFile(file)
  File "d:\work\dewnr\logging_software\las_reader\las_reader\las.py", line 131, in __init__
    self.read(file, **kwargs)
  File "d:\work\dewnr\logging_software\las_reader\las_reader\las.py", line 156, in read
    data = reader.read_data(len(self.curves))
  File "d:\work\dewnr\logging_software\las_reader\las_reader\las.py", line 445, in read_data
    arr = numpy.reshape(arr, (-1, number_of_curves))
  File "C:\Users\kent\Anaconda\lib\site-packages\numpy\core\fromnumeric.py", line 221, in reshape
    return reshape(newshape, order=order)
ValueError: total size of new array must be unchanged
```

**Comment by kinverarity1** [comment]
This is actually the error message caused by #6 (unable to support wrapped data).
