### ISSUE TITLE
LASDataError: Failed to read data: ValueError: invalid literal for float(): 2000.0:

### ISSUE THREAD

**Issue by kinverarity1** [kinverarity1/las-reader#22]
```
D:\study\2015\las_kgs_test\1999\1999\1006347031.las
Traceback (most recent call last):
  File ".\basic_read_test.py", line 20, in <module>
    l = las_reader.read(fn)
  File "d:\work\dewnr\logging_software\las_reader\las_reader\__init__.py", line 5, in read
    return las.LASFile(file)
  File "d:\work\dewnr\logging_software\las_reader\las_reader\las.py", line 132, in __init__
    self.read(file, **kwargs)
  File "d:\work\dewnr\logging_software\las_reader\las_reader\las.py", line 157, in read
    data = reader.read_data(len(self.curves))
  File "d:\work\dewnr\logging_software\las_reader\las_reader\las.py", line 436, in read_data
    traceback.format_exc()))
LASDataError: Failed to read data:
Traceback (most recent call last):
  File "d:\work\dewnr\logging_software\las_reader\las_reader\las.py", line 433, in read_data
    arr = numpy.loadtxt(StringIO(s))
  File "C:\Users\kent\Anaconda\lib\site-packages\numpy\lib\npyio.py", line 856, in loadtxt
    items = [conv(val) for (conv, val) in zip(converters, vals)]
ValueError: invalid literal for float(): 2000.0:
```

**Comment by kinverarity1** [comment]
``las_reader`` is breaking on the colon in the ~A section but the problems are more extensive than that. I'm going to ignore it.

```
~CURVE INFORMATION BLOCK
#MNEM.UNIT      API CODE      Curve Description
#---------    -------------   ---------------------------------
 DEPT                                              .F                                00 000 00 00: 1  Depth Curve
 GR                                                .GAPI                              7 310  1  0: 10  GAMMA RAY
 SP                                                .MV                                7  10  1  0: 9  SPONTANEOUS POTENTIAL
 ILD                                               .OHMM                              7 120 46  0: 8  INDUCTION LOG, DEEP
 ILM                                               .OHMM                              7 120 44  0: 7  INDUCTION LOG, MEDIUM
 SFLU                                              .OHMM                              7 220  1  0: 6  SFL UNAVERAGED
~Parameter Information Block
 UM32                                              .B/CC                               50000.0000: U Matrix Min 2-3 Min Model
 UM33                                              .B/CC                               50000.0000: U Matrix Min 3-3 Min Model
 DFD                                               .LB/G                               50000.0000: Mud Weight
 SPFG                                              .----                               50000.0000: FLAG, SP Comp.
 ~A DEPT      GR      SP     ILD      ILM      SFLU.                                             : 
 1623                                              .0     33.0     -31    36.0   2000.0    2000.0: 
 1624                                              .0     27.0     -29    34.2   2000.0    2000.0: 
 1625                                              .0     21.1     -28    31.4   2000.0    2000.0: 
 1626                                              .0     17.3     -25    34.6   2000.0    2000.0: 
```
