### ISSUE TITLE
LASHeaderError: Failed in ~C section on line: .RILD.Ohm-m                   : DIL Deep Resistivity

### ISSUE THREAD

**Issue by kinverarity1** [kinverarity1/las-reader#25]
```
D:\study\2015\las_kgs_test\2006_2011\1043994644.las
Traceback (most recent call last):
  File ".\basic_read_test.py", line 20, in <module>
    l = las_reader.read(fn)
  File "d:\work\dewnr\logging_software\las_reader\las_reader\__init__.py", line 5, in read
    return las.LASFile(file)
  File "d:\work\dewnr\logging_software\las_reader\las_reader\las.py", line 132, in __init__
    self.read(file, **kwargs)
  File "d:\work\dewnr\logging_software\las_reader\las_reader\las.py", line 150, in read
    self.curves = reader.read_list_section('~C')
  File "d:\work\dewnr\logging_software\las_reader\las_reader\las.py", line 424, in read_list_section
    section_name, line, traceback.format_exc()))
LASHeaderError: Failed in ~C section on line:
.RILD.Ohm-m                   : DIL Deep Resistivity
Traceback (most recent call last):
  File "d:\work\dewnr\logging_software\las_reader\las_reader\las.py", line 421, in read_list_section
    values = read_line(line)
  File "d:\work\dewnr\logging_software\las_reader\las_reader\las.py", line 529, in read_line
    for key, value in m.groupdict().items():
AttributeError: 'NoneType' object has no attribute 'groupdict'
```

**Comment by kinverarity1** [comment]
I see this file is using the period to demarcate duplicate curve mnemonics:

```
~Curve Information Block
DEPT.FT            0 000 00 00: Depth
.RILD.Ohm-m                   : DIL Deep Resistivity
.RILM.Ohm-m                   : DIL Medium Resistivity
CNPOR.pu                      : CN Selected Porosity
DCAL.in                       : CDL Caliper
DPOR.pu                       : CDL Density Porosity
GR.GAPI                       : Gamma Ray
RHOB.g/cc                     : CDL Bulk Density
RHOC.g/cc                     : CDL Density Correction
RILD.Ohm-m                    : DIL Deep Resistivity
RILM.Ohm-m                    : DIL Medium Resistivity
```

But the use of a period at the start of the line seems counter to the LAS spec. Instead I'm going to ignore the leading period and use ``las_reader``'s existing approach to duplicate mnemonics which is to append an index:

```
[Curve(mnemonic='DEPT', unit='FT', value='0 000 00 00', descr='Depth', data=array([  0.00000000e+00,   5.00000000e-01,   1.00000000e+00, ...,
          4.59700000e+03,   4.59750000e+03,   4.59800000e+03])),
 Curve(mnemonic='RILD[0]', unit='Ohm-m', value='', descr='DIL Deep Resistivity', data=array([  3.3192,   0.7585,   1.6338, ...,  50.6924,  51.8272,  52.0517])),
 Curve(mnemonic='RILM[0]', unit='Ohm-m', value='', descr='DIL Medium Resistivity', data=array([     nan,      nan,      nan, ...,  45.6886,  45.7489,  45.6162])),
 Curve(mnemonic='CNPOR', unit='pu', value='', descr='CN Selected Porosity', data=array([ nan,  nan,  nan, ...,  nan,  nan,  nan])),
 Curve(mnemonic='DCAL', unit='in', value='', descr='CDL Caliper', data=array([ nan,  nan,  nan, ...,  nan,  nan,  nan])),
 Curve(mnemonic='DPOR', unit='pu', value='', descr='CDL Density Porosity', data=array([ nan,  nan,  nan, ...,  nan,  nan,  nan])),
 Curve(mnemonic='GR', unit='GAPI', value='', descr='Gamma Ray', data=array([ 459.383 ,  541.8128,  575.702 , ...,       nan,       nan,
              nan])),
 Curve(mnemonic='RHOB', unit='g/cc', value='', descr='CDL Bulk Density', data=array([ nan,  nan,  nan, ...,  nan,  nan,  nan])),
 Curve(mnemonic='RHOC', unit='g/cc', value='', descr='CDL Density Correction', data=array([ nan,  nan,  nan, ...,  nan,  nan,  nan])),
 Curve(mnemonic='RILD[1]', unit='Ohm-m', value='', descr='DIL Deep Resistivity', data=array([ 3.3192,  0.7585,  1.6338, ...,     nan,     nan,     nan])),
 Curve(mnemonic='RILM[1]', unit='Ohm-m', value='', descr='DIL Medium Resistivity', data=array([ nan,  nan,  nan, ...,  nan,  nan,  nan])),
```
