### ISSUE TITLE
LASHeaderError: Failed in ~W section on line: INJUN                  815.00

### ISSUE THREAD

**Issue by kinverarity1** [kinverarity1/las-reader#28]
```
D:\study\2015\las_kgs_test\LAS Files\D-D' LAS Files\Birney\Birney_A.LAS
Traceback (most recent call last):
  File ".\basic_read_test.py", line 20, in <module>
    l = las_reader.read(fn)
  File "d:\work\dewnr\logging_software\las_reader\las_reader\__init__.py", line 5, in read
    return las.LASFile(file)
  File "d:\work\dewnr\logging_software\las_reader\las_reader\las.py", line 132, in __init__
    self.read(file, **kwargs)
  File "d:\work\dewnr\logging_software\las_reader\las_reader\las.py", line 149, in read
    self.well = reader.read_section('~W')
  File "d:\work\dewnr\logging_software\las_reader\las_reader\las.py", line 411, in read_section
    section_name, line, traceback.format_exc()))
LASHeaderError: Failed in ~W section on line:
INJUN                  815.00
Traceback (most recent call last):
  File "d:\work\dewnr\logging_software\las_reader\las_reader\las.py", line 408, in read_section
    values = read_line(line)
  File "d:\work\dewnr\logging_software\las_reader\las_reader\las.py", line 529, in read_line
    for key, value in m.groupdict().items():
AttributeError: 'NoneType' object has no attribute 'groupdict'
```

**Comment by kinverarity1** [comment]
This avowedly LAS 2.0 file doesn't even come close to complying with the spec or even remotely helpful for any software to parse given the abbreviating periods in there. I'm going to leave this as an error and close the issue.

```
CNTY.        HARRISON                          : COUNTY          
LOC.         1266'FNL & 1966'FWL OF NW1/4   : LOCATION DESC   
#~TOPS
INJUN                  815.00
BEREA                 1410.00
DEV. SHALE            1460.00
BIG LIME              4628.00
ORISKANY              4805.00
PACKER SHELL          6662.00
ORDOV. SHALE          6971.00
TRENTON               8612.00
BLACK RIVER           8880.00
GULL RIVER            9438.00
GLENWOOD SHALE        9500.00
BEEKMANTOWN           9654.00
ROSE RUN SD.         10168.00
```
