### ISSUE TITLE
Fails on LAS file spec version 2.1 (?)

### ISSUE THREAD

**Issue by kinverarity1** [kinverarity1/las-reader#29]
```
D:\study\2015\las_kgs_test\LAS Files\E-E' LAS Files\Deem\A_Deem_B.las
Traceback (most recent call last):
  File ".\basic_read_test.py", line 20, in <module>
    l = las_reader.read(fn)
  File "d:\work\dewnr\logging_software\las_reader\las_reader\__init__.py", line 5, in read
    return las.LASFile(file)
  File "d:\work\dewnr\logging_software\las_reader\las_reader\las.py", line 132, in __init__
    self.read(file, **kwargs)
  File "d:\work\dewnr\logging_software\las_reader\las_reader\las.py", line 149, in read
    self.well = reader.read_section('~W')
  File "d:\work\dewnr\logging_software\las_reader\las_reader\las.py", line 403, in read_section
    parser = SectionParser(section_name, version=self.version)
  File "d:\work\dewnr\logging_software\las_reader\las_reader\las.py", line 487, in __init__
    section_orders = ORDER_DEFINITIONS[self.version][self.section_name2]
KeyError: 2.1
```

**Comment by kinverarity1** [comment]
Fixed by assuming version < 2 is 1.2 and >= 2 && < 3 is 2.0. Code now gives a warning. See [test notebook](https://github.com/kinverarity1/las-reader/blob/master/docs/issue%20notebooks/issue%20%2321%20-%20fails%20on%20LAS%202.1.ipynb)
