### ISSUE TITLE
Trying to read a file providing wrong file path gives a confusing VERS exception

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [kinverarity1/las-reader#47]
Often when the file name path is badly setup, I got this kind of exception.
file_ref parameter is considered to be string content of the file path:
```file_ref: either a filename, an open file object, or a string of a LAS file contents.```

Suggestion: if file_ref is a single line string to be all the time consider as file path and if don't exist to have a clear message that file path doesn't exist instead of trying to parse the file path as LAS content as shown below:

```
Mac$ python3
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 23 2015, 02:52:03) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from las_reader import read
>>> l = read('random/Text/Or/Bad/File/Name', autodetect_encoding=True)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/las_reader/las.py", line 174, in read
    reader.version = self.version['VERS'].value
KeyError: 'VERS'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/las_reader/__init__.py", line 26, in read
    autodetect_encoding_chars=autodetect_encoding_chars)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/las_reader/las.py", line 146, in __init__
    autodetect_encoding_chars=autodetect_encoding_chars)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/las_reader/las.py", line 176, in read
    raise KeyError("No key VERS in ~V section")
KeyError: 'No key VERS in ~V section'

```

**Comment by VelizarVESSELINOV** [comment]
Thanks, much appreciated :+1:
